# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers.python.flatbuffers as flatbuffers

class FlakiRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFlakiRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlakiRequest()
        x.Init(buf, n + offset)
        return x

    # FlakiRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FlakiRequestStart(builder): builder.StartObject(0)
def FlakiRequestEnd(builder): return builder.EndObject()
