# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import flatbuffers.python.flatbuffers as fb

builder = fb.Builder(0)

class FlakiStub(object):
  
  def __init__(self, channel):
    """Constructor.
    
    Args:
      channel: A grpc.Channel.
    """
    self.NextID = channel.unary_unary(
        '/fb.Flaki/NextID',
        request_serializer=builder.SerializeToString,
        response_deserializer=builder.FromString,
        )
    self.NextValidID = channel.unary_unary(
        '/fb.Flaki/NextValidID',
        request_serializer=builder.SerializeToString,
        response_deserializer=builder.FromString,
        )


class FlakiServicer(object):
  
  def NextID(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')
  
  def NextValidID(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FlakiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'NextID': grpc.unary_unary_rpc_method_handler(
          servicer.NextID,
          request_deserializer=builder.FromString,
          response_serializer=builder.SerializeToString,
      ),
      'NextValidID': grpc.unary_unary_rpc_method_handler(
          servicer.NextValidID,
          request_deserializer=builder.FromString,
          response_serializer=builder.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fb.Flaki', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  import flatbuffers.python.flatbuffers as fb
  
  builder = fb.Builder(0)
  
  class FlakiStub(object):
    
    def __init__(self, channel):
      """Constructor.
      
      Args:
        channel: A grpc.Channel.
      """
      self.NextID = channel.unary_unary(
          '/fb.Flaki/NextID',
          #request_serializer=builder.SerializeToString,
          #response_deserializer=builder.FromString,
          )
      self.NextValidID = channel.unary_unary(
          '/fb.Flaki/NextValidID',
          #request_serializer=builder.SerializeToString,
          #response_deserializer=builder.FromString,
          )
  
  
  class FlakiServicer(object):
    
    def NextID(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')
    
    def NextValidID(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')
  
  
  def add_FlakiServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'NextID': grpc.unary_unary_rpc_method_handler(
            servicer.NextID,
            #request_deserializer=builder.FromString,
            #response_serializer=builder.SerializeToString,
        ),
        'NextValidID': grpc.unary_unary_rpc_method_handler(
            servicer.NextValidID,
            #request_deserializer=builder.FromString,
            #response_serializer=builder.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'fb.Flaki', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
  
  
  class BetaFlakiServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.
    
    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def NextID(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def NextValidID(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  
  
  class BetaFlakiStub(object):
    """The Beta API is deprecated for 0.15.0 and later.
    
    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def NextID(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    NextID.future = None
    def NextValidID(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    NextValidID.future = None
  
  
  def beta_create_Flaki_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.
    
    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('fb.Flaki', 'NextID'): builder.FromString,
      ('fb.Flaki', 'NextValidID'): builder.FromString,
    }
    response_serializers = {
      ('fb.Flaki', 'NextID'): builder.SerializeToString,
      ('fb.Flaki', 'NextValidID'): builder.SerializeToString,
    }
    method_implementations = {
      ('fb.Flaki', 'NextID'): face_utilities.unary_unary_inline(servicer.NextID),
      ('fb.Flaki', 'NextValidID'): face_utilities.unary_unary_inline(servicer.NextValidID),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)
  
  
  def beta_create_Flaki_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.
    
    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('fb.Flaki', 'NextID'): builder.SerializeToString,
      ('fb.Flaki', 'NextValidID'): builder.SerializeToString,
    }
    response_deserializers = {
      ('fb.Flaki', 'NextID'): builder.FromString,
      ('fb.Flaki', 'NextValidID'): builder.FromString,
    }
    cardinalities = {
      'NextID': cardinality.Cardinality.UNARY_UNARY,
      'NextValidID': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'fb.Flaki', cardinalities, options=stub_options)
except ImportError:
  pass