# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers.python.flatbuffers as flatbuffers

class FlakiReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFlakiReply(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlakiReply()
        x.Init(buf, n + offset)
        return x

    # FlakiReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlakiReply
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

def FlakiReplyStart(builder): builder.StartObject(1)
def FlakiReplyAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def FlakiReplyEnd(builder): return builder.EndObject()
